### ISSUE TITLE
Three failures tied to GRanges RDS object

### ISSUE THREAD

**Issue by hargreaw** [LTLA/rds2cpp#6]
libc++abi: terminating with uncaught exception of type std::runtime_error: failed to parse an S4 object's body
  - failed to parse a pairlist body
  - failed to parse an S4 object's body
  - failed to detect class attribute in an S4 object
[1]    30318 abort      python tests/temp.py

**Comment by LTLA** [comment]
It's actually one error's traceback. Closed in 11cf1421eb550145d268ad92f31a66a7abde8048.
